[tool.poetry]
name = "glue-etl-pipeline"
version = "0.1.0"
description = "AWS Glue ETL pipeline"
authors = ["Francesco Gastaldello"]

[tool.poetry.dependencies]
python = "^3.6.2"
black = "^21.12b0"
Cerberus = "1.3.3"
awscli = "^1.22.37"
boto3 = "1.20.37"
pyarrow = "^6.0.1"
pypandoc = "^1.7.2"
pyspark = "2.4.3"
elasticsearch = "^7.17.0"
coverage = "6.2"
coverage-badge = "^1.1.0"
s3fs = "0.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
